### ISSUE TITLE
Images for new ingredients are broken

### ISSUE THREAD

**Issue by VenatusSimpleX** [orz-tools/cpp#11]
Hi, thank you for the tool! It seems that the ingredients for the new update is broken, so I am unsure of what each name is since the translation is a bit different too.

![image](https://github.com/orz-tools/cpp/assets/31540342/acb31716-8568-415f-b785-6fa3554a9add)

**Comment by orzFly** [comment]
Apologies, but they are intentional. Someone else have received copyright claims from the developer of Reverse 1999 on certain public GitHub repositories containing unpacked assets, and as a result, I lack the sources for these in-game icons. Even if I unpack these assets myself, I am unable to distribute them.

Regarding hand-drawn replacements, particularly for items introduced in v1.4, our artist is currently not dedicating any time to this task. If you are able to create these icons in a similar style, I would gladly incorporate them.

**Comment by VenatusSimpleX** [comment]
Hi, I directed my partner's attention to this post and it seems she wants to try out due to my interest in the situation. This is her attempt in drawing 双蛇权杖 in similar style to the image that we see on the page. Attached is the original picture for reference, and her representation of it, please let me know what you think.

Original:
![image](https://github.com/orz-tools/cpp/assets/31540342/7ed0728b-99b6-400a-9637-d2506905d40a)

Her representation:
![image](https://github.com/orz-tools/cpp/assets/31540342/b1227c77-a408-4d37-937b-7d7bea03762e)

**Comment by orzFly** [comment]
That's cool! It's almost there. There are two more points to take note of:

1. Try to preview it after scaling down (You may want to download all the icons and preview them in Explorer in thumbnail view).
2. Please make sure they are 256px*256px PNGs with transparent background.

These images are stored on [this repo](https://github.com/orz-tools/cpp-soul/tree/master/reverse1999/items). Feel free to send pull requests there, even if it's just one icon!

By the way, that repo is licensed under [CC0 1.0 Universal](https://github.com/orz-tools/cpp-soul/blob/master/LICENSE). Will this work for you & your partner?

**Comment by VenatusSimpleX** [comment]
Thank you, I will let her know that her drawing is good 👍, other than that, note taken, I will crop/resize the image to 256x256 and set background to transparent before submission. The license is ok for us, just happy that we get to contribute.

But not too understand about 1., do you mean that you are asking me to clone https://github.com/orz-tools/cpp-soul first and view the icons in thumbnail mode to make sure we can recognise it?

**Comment by orzFly** [comment]
> But not too understand about 1., do you mean that you are asking me to clone [orz-tools/cpp-soul](https://github.com/orz-tools/cpp-soul) first and view the icons in thumbnail mode to make sure we can recognise it?

Apologies for any confusion. In most cases, icons are presented in a smaller size, around 40-60px in the Inventory and approximately 30px in the looting list. I meant to convey that you should also consider whether it looks good at those reduced size.

**Comment by VenatusSimpleX** [comment]
Ah i think i understand, so just to clarify:
1. source image should be 256x256
2. image should look nice when scaled to 30px, 40px, and 60px

Is correct?

**Comment by orzFly** [comment]
@VenatusSimpleX Exactly!

**Comment by orzFly** [comment]
A workaround has been applied. Images should work now.

Contributions to hand-drawn replacements are stoll needed and welcomed.
