### ISSUE TITLE
How to get game data from Reverse 1999?

### ISSUE THREAD

**Issue by PetalTempest** [orz-tools/cpp#12]
Hello! 
I'm curious how to extract the game data from Reverse 1999.
![image](https://github.com/orz-tools/cpp/assets/109507817/b18efcd9-2c8e-4411-b3b7-bb4a99ce82df)
I am working on a similar project for the Global version. A way to extract the data would help a lot!

Thank you for your time! 💕

**Comment by orzFly** [comment]
Sorry, game data are provided by one contributor. I have no ideas on that.

Also, someone else have received copyright claims from the developer of Reverse 1999 on certain public GitHub repositories containing unpacked assets. I cannot tell you even if I know.

Locked as off-topic.
