### ISSUE TITLE
Is it possible to minimize “关于” and “更新日志”？

### ISSUE THREAD

**Issue by kebingyu** [orz-tools/cpp#5]
These two columns take about 1/3 of the width.

**Comment by oott123** [comment]
You can drag the horizontal scroll bar to hide them. Sorry for any inconvenience, but it is designed this way.

**Comment by orzFly** [comment]
The "About" and "Change Log" sections take up approximately 600px in width, leaving approximately 2160px for the remaining part. If you consider that 600px occupies 1/3 of the screen width, then your screen is roughly 1800px, which is not sufficient to display the remaining content. Thus, a horizontal scrollbar will still be necessary.
